"""empty message

Revision ID: 3617b74fe7d1
Revises: 92cb5dfd5e7a
Create Date: 2021-02-04 13:53:01.662349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3617b74fe7d1'
down_revision = '92cb5dfd5e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('blog_info', sa.String(), nullable=True))
    op.alter_column('category', 'category_all',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('works', sa.Column('categoryId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'works', 'category', ['categoryId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'categoryId')
    op.alter_column('category', 'category_all',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.drop_column('blog', 'blog_info')
    # ### end Alembic commands ###
