"""empty message

Revision ID: 4b7f10649a82
Revises: d8a5d9974aa5
Create Date: 2021-02-04 14:07:48.800510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7f10649a82'
down_revision = 'd8a5d9974aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('categoryId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'works', 'category', ['categoryId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'categoryId')
    # ### end Alembic commands ###
