"""empty message

Revision ID: d8a5d9974aa5
Revises: 3617b74fe7d1
Create Date: 2021-02-04 14:06:02.387359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a5d9974aa5'
down_revision = '3617b74fe7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'category_all',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.add_column('works', sa.Column('categoryId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'works', 'category', ['categoryId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'works', type_='foreignkey')
    op.drop_column('works', 'categoryId')
    op.alter_column('category', 'category_all',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
